laravel-modules-examples/Books/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'prefix' => 'letterbooks', 'namespace' => 'Modules\Books\Http\Controllers'], function()
{
    Route::get('/data', 'BooksController@dataList')->name('books.data.list');
    Route::get('/{id}/data', 'BooksController@dataItem')->name('books.data.item');

    Route::get('/', 'BooksController@index')->name('books.index');
    Route::get('/{id}', 'BooksController@show')->name('books.item');
});

Route::group(
    ['middleware' => 'auth:api', 'prefix' => '/api/v1/letterbooks', 'namespace' => 'Modules\Books\Http\Controllers\Api'],
    function() {
        Route::get('/', 'ApiController@index')->name('api.books.index');
        Route::get('/{id}', 'ApiController@show')->name('api.books.show');
        Route::post('/', 'ApiController@store')->name('api.books.create');
        Route::post('/{id}', 'ApiController@update')->name('api.books.update');
        Route::delete('/{id}', 'ApiController@destroy')->name('api.books.delete');

        // Pdf
        Route::post('/{id}/pdf', 'ApiController@updatePdf')
            ->name('api.books.pdf.update');
        Route::delete('/{id}/pdf', 'ApiController@destroyPdf')
            ->name('api.books.pdf.delete');

        // Pdf Text
        Route::post('/{id}/pdf-text', 'ApiController@updatePdfText')
            ->name('api.books.pdf_text.update');
        Route::delete('/{id}/pdf-text', 'ApiController@destroyPdfText')
            ->name('api.books.pdf_text.delete');
    }
);

laravel-modules-examples/Books/Entities/Book.php
<?php

namespace Modules\Books\Entities;

use App\Entities\Interfaces\GqlEntity;
use App\Entities\Traits\EsSearchable;
use Illuminate\Database\Eloquent\Model;
use Modules\Books\Es\Documents\BookDoc;
use Modules\Books\GraphQL\Types\LetterBookType;
use App\Entities\Interfaces\ContentInterface;
use Modules\Common\Entities\Interfaces\EntityThumbInterface;
use App\Entities\Interfaces\ReferenceInterface;
use App\Entities\Traits\ContentTrait;
use App\Entities\Traits\References;
use Modules\Common\Entities\Traits\ThumbnailTrait;
use Modules\Media\Entities\Interfaces\MediaLibraryInterface;
use Modules\Media\Entities\MediaTrait;
use Modules\Taxonomy\Entities\Traits\TaxonomyTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Media;

class Book extends Model implements
    HasMediaConversions,
    EntityThumbInterface,
    ReferenceInterface,
    MediaLibraryInterface,
    ContentInterface,
    GqlEntity
{
    use MediaTrait, ThumbnailTrait, References, ContentTrait, EsSearchable, TaxonomyTrait;

    const PDF_MEDIA_COLLECTION_NAME = 'medium_resolution';
    const PDF_TEXT_MEDIA_COLLECTION_NAME = 'text_copy';

    protected $fillable = [
        'title', 'body', 'date'
    ];

    protected $casts = [
        'metadata' => 'object',
    ];

    protected $table = 'content_books';

    protected $mappingName = 'book';

    protected $contentTypeName = 'book';

    protected $routeName = 'books.item';

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(150)
            ->sharpen(10);
    }

    /**
     * Get snippet thumbnail url
     *
     * @return string
     */
    public function getThumbSitePathAttribute($value = ''): string
    {

        $thumb = '';
        if ($this->pdf) {
            $thumb = $this->pdf->getPath('thumb');
        }elseif ($this->txt) {
            $thumb = $this->txt->getPath('thumb');
        }
        $thumb = str_replace(base_path('storage'), '', $thumb);

        return $thumb ?: $this->getDefaultThumbSitePathAttribute($value);
    }

    /**
     * Get pdf file relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function pdf()
    {
        return $this->morphOne(config('medialibrary.media_model'), 'model')
            ->where('collection_name', '=', self::PDF_MEDIA_COLLECTION_NAME);
    }

    /**
     * Get pdf file relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function pdf_text()
    {
        return $this->morphOne(config('medialibrary.media_model'), 'model')
            ->where('collection_name', '=', self::PDF_TEXT_MEDIA_COLLECTION_NAME);
    }

    public function getGqlType(): string
    {
        return (new LetterBookType())->name;
    }

    public function toSearchableArray()
    {
        return (new BookDoc($this))->source();
    }
}

laravel-modules-examples/Books/Resources/views/index.blade.php
@extends('page-base')

@section('stylesheets')

@endsection

@section('page-header')
    <h1>W.C. White Letter Books</h1>
@stop

@section('content')
    <div class="row">
        <table class="table table-bordered" id="book-data-table">
            <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Date</th>
                <th>Number</th>
                <th>Status</th>
            </tr>
            </thead>
        </table>
    </div>
@endsection

@push('scripts')
<script>
    $(function() {
        $('#book-data-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('books.data') !!}',
            pageLength: 50,
            lengthMenu: [ 25, 50, 100, 250,  ],
            columns: [
                { data: 'title', name: 'title' },
                { data: 'author', name: 'author', searchable: false },
                { data: 'date', name: 'date', searchable: false },
                { data: 'number', name: 'number', searchable: false },
                { data: 'status', name: 'status', searchable: false },
            ]
        });
    });
</script>
@endpush

laravel-modules-examples/Books/Resources/views/show.blade.php
@extends('page-base')

@section('stylesheets')

@endsection

@section('page-header')
    <h1>{{ $book->title }}</h1>
@stop

@php


@endphp

@section('content')
    <div class="row media-letterbook">
        <div class="col-md-9">
            <letterbook
                first-pdf-path="{{ $pdf_path ?: null }}"
                first-pdf-url="{{ $pdf_url ?: null  }}"
                second-pdf-path="{{ $pdf_text_path ?: null  }}"
                second-pdf-url="{{ $pdf_text_url ?: null  }}"
            ></letterbook>
        </div>

        <div id="book-info" class="col-md-3 media-metadata">
            <div class="panel panel-default row">
                <div class="panel-heading"><h4>Metadata</h4></div>
                
                <div class="panel-body">
                    @if ($book->thumb_site_path)
                        <div class="text-center media-metadata__thumb">
                            <img src="{{ $book->thumb_site_path }}" alt="">
                        </div>
                    @endif
                    @if($author = $book->metadata->author)
                        <div><b>Author:</b> {{ $author }}</div>
                    @endif
                    @if($number = $book->metadata->number)
                        <div><b>Number:</b> {{ $number }}</div>
                    @endif
                    @if($status = $book->metadata->status)
                        <div><b>Status:</b> {{ $status }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        
    </script>
@endpush